{
  "document": {
    "aggregate_severity": {
      "namespace": "https://openanolis.cn/sig/SIG-Infra/doc/1014149186600348472",
      "text": "Moderate"
    },
    "category": "csaf_vex",
    "csaf_version": "2.0",
    "distribution": {
      "text": "Copyright Â© OpenAnolis.cn All rights reserved",
      "tlp": {
        "label": "WHITE",
        "url": "https://www.first.org/tlp/"
      }
    },
    "lang": "en",
    "notes": [
      {
        "category": "summary",
        "text": "OpenAnolis ANSA-2022:0700",
        "title": "Title"
      },
      {
        "category": "description",
        "text": "python3 security update",
        "title": "Description of the Errata"
      },
      {
        "category": "legal_disclaimer",
        "text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to OpenAnolis. and provide a link to the original.",
        "title": "Terms of Use"
      }
    ],
    "publisher": {
      "category": "vendor",
      "contact_details": "https://openanolis.cn/page/contact",
      "issuing_authority": "OpenAnolis Product Security is responsible for vulnerability handling across all OpenAnolis offerings.",
      "name": "Anolis OS Product Security Team",
      "namespace": "https://openanolis.cn/"
    },
    "references": [
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      },
      {
        "RefID": "",
        "RefURL": "",
        "Source": ""
      }
    ],
    "title": "OpenAnolis Errata ANSA-2022:0700",
    "tracking": {
      "current_release_date": "2022-11-30 10:05:08",
      "id": "ANSA-2022:0700",
      "initial_release_date": "2022-09-21 18:03:27",
      "revision_history": [
        {
          "date": "2022-09-21 18:03:27",
          "number": "1",
          "summary": "Initial version"
        },
        {
          "date": "2022-11-30 10:05:08",
          "number": "2",
          "summary": "Current version"
        }
      ]
    }
  },
  "product_tree": {
    "branches": [
      {
        "branches": [
          {
            "branches": [
              {
                "category": "product_name",
                "name": "Anolis OS 8",
                "product": {
                  "name": "Anolis OS 8",
                  "product_id": "Anolis OS 8",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              }
            ],
            "category": "product_family",
            "name": "OpenAnolis Linux"
          },
          {
            "branches": [
              {
                "category": "product_version",
                "name": "platform-python-3.6.8-47.0.1.an8_6.aarch64",
                "product": {
                  "name": "platform-python-3.6.8-47.0.1.an8_6.aarch64",
                  "product_id": "platform-python-3.6.8-47.0.1.an8_6.aarch64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
                "product": {
                  "name": "platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
                  "product_id": "platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
                "product": {
                  "name": "platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
                  "product_id": "platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "python3-idle-3.6.8-47.0.1.an8_6.aarch64",
                "product": {
                  "name": "python3-idle-3.6.8-47.0.1.an8_6.aarch64",
                  "product_id": "python3-idle-3.6.8-47.0.1.an8_6.aarch64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "python3-libs-3.6.8-47.0.1.an8_6.aarch64",
                "product": {
                  "name": "python3-libs-3.6.8-47.0.1.an8_6.aarch64",
                  "product_id": "python3-libs-3.6.8-47.0.1.an8_6.aarch64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "python3-test-3.6.8-47.0.1.an8_6.aarch64",
                "product": {
                  "name": "python3-test-3.6.8-47.0.1.an8_6.aarch64",
                  "product_id": "python3-test-3.6.8-47.0.1.an8_6.aarch64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
                "product": {
                  "name": "python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
                  "product_id": "python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              }
            ],
            "category": "architecture",
            "name": "aarch64"
          },
          {
            "branches": [
              {
                "category": "product_version",
                "name": "python3-3.6.8-47.0.1.an8_6.src",
                "product": {
                  "name": "python3-3.6.8-47.0.1.an8_6.src",
                  "product_id": "python3-3.6.8-47.0.1.an8_6.src",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              }
            ],
            "category": "architecture",
            "name": "src"
          },
          {
            "branches": [
              {
                "category": "product_version",
                "name": "platform-python-3.6.8-47.0.1.an8_6.x86_64",
                "product": {
                  "name": "platform-python-3.6.8-47.0.1.an8_6.x86_64",
                  "product_id": "platform-python-3.6.8-47.0.1.an8_6.x86_64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
                "product": {
                  "name": "platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
                  "product_id": "platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
                "product": {
                  "name": "platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
                  "product_id": "platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "python3-idle-3.6.8-47.0.1.an8_6.x86_64",
                "product": {
                  "name": "python3-idle-3.6.8-47.0.1.an8_6.x86_64",
                  "product_id": "python3-idle-3.6.8-47.0.1.an8_6.x86_64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "python3-libs-3.6.8-47.0.1.an8_6.x86_64",
                "product": {
                  "name": "python3-libs-3.6.8-47.0.1.an8_6.x86_64",
                  "product_id": "python3-libs-3.6.8-47.0.1.an8_6.x86_64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "python3-test-3.6.8-47.0.1.an8_6.x86_64",
                "product": {
                  "name": "python3-test-3.6.8-47.0.1.an8_6.x86_64",
                  "product_id": "python3-test-3.6.8-47.0.1.an8_6.x86_64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              },
              {
                "category": "product_version",
                "name": "python3-tkinter-3.6.8-47.0.1.an8_6.x86_64",
                "product": {
                  "name": "python3-tkinter-3.6.8-47.0.1.an8_6.x86_64",
                  "product_id": "python3-tkinter-3.6.8-47.0.1.an8_6.x86_64",
                  "product_identification_helper": {
                    "cpe": "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:*"
                  }
                }
              }
            ],
            "category": "architecture",
            "name": "x86_64"
          }
        ],
        "category": "vendor",
        "name": "OpenAnolis"
      }
    ],
    "relationships": [
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "platform-python-3.6.8-47.0.1.an8_6.aarch64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64"
        },
        "product_reference": "platform-python-3.6.8-47.0.1.an8_6.aarch64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "platform-python-debug-3.6.8-47.0.1.an8_6.aarch64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64"
        },
        "product_reference": "platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "platform-python-devel-3.6.8-47.0.1.an8_6.aarch64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64"
        },
        "product_reference": "platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "python3-idle-3.6.8-47.0.1.an8_6.aarch64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64"
        },
        "product_reference": "python3-idle-3.6.8-47.0.1.an8_6.aarch64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "python3-libs-3.6.8-47.0.1.an8_6.aarch64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64"
        },
        "product_reference": "python3-libs-3.6.8-47.0.1.an8_6.aarch64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "python3-test-3.6.8-47.0.1.an8_6.aarch64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64"
        },
        "product_reference": "python3-test-3.6.8-47.0.1.an8_6.aarch64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "python3-tkinter-3.6.8-47.0.1.an8_6.aarch64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64"
        },
        "product_reference": "python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "platform-python-3.6.8-47.0.1.an8_6.x86_64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64"
        },
        "product_reference": "platform-python-3.6.8-47.0.1.an8_6.x86_64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "platform-python-debug-3.6.8-47.0.1.an8_6.x86_64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64"
        },
        "product_reference": "platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "platform-python-devel-3.6.8-47.0.1.an8_6.x86_64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64"
        },
        "product_reference": "platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "python3-idle-3.6.8-47.0.1.an8_6.x86_64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64"
        },
        "product_reference": "python3-idle-3.6.8-47.0.1.an8_6.x86_64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "python3-libs-3.6.8-47.0.1.an8_6.x86_64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64"
        },
        "product_reference": "python3-libs-3.6.8-47.0.1.an8_6.x86_64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "python3-test-3.6.8-47.0.1.an8_6.x86_64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64"
        },
        "product_reference": "python3-test-3.6.8-47.0.1.an8_6.x86_64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "python3-tkinter-3.6.8-47.0.1.an8_6.x86_64 as component of Anolis OS 8",
          "product_id": "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        },
        "product_reference": "python3-tkinter-3.6.8-47.0.1.an8_6.x86_64",
        "relates_to_product_reference": "Anolis OS 8"
      },
      {
        "category": "default_component_of",
        "full_product_name": {
          "name": "python3-3.6.8-47.0.1.an8_6.src as component of Anolis OS 8",
          "product_id": "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src"
        },
        "product_reference": "python3-3.6.8-47.0.1.an8_6.src",
        "relates_to_product_reference": "Anolis OS 8"
      }
    ]
  },
  "vulnerabilities": [
    {
      "cve": "CVE-2015-20107",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2015-20107"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "In Python (aka CPython) through 3.10.4, the mailcap module does not add escape characters into commands discovered in the system mailcap file. This may allow attackers to inject shell commands into applications that call mailcap.findmatch with untrusted input (if they lack validation of user-provided filenames or arguments).",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "LOW",
            "attackVector": "NETWORK",
            "availabilityImpact": "LOW",
            "baseScore": 7.1,
            "baseSeverity": "HIGH",
            "confidentialityImpact": "NONE",
            "integrityImpact": "HIGH",
            "privilegesRequired": "LOW",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:L",
            "version": "3.1",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Important"
        }
      ],
      "title": "CVE-2015-20107"
    },
    {
      "cve": "CVE-2019-16056",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2019-16056"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "An issue was discovered in Python through 2.7.16, 3.x through 3.5.7, 3.6.x through 3.6.9, and 3.7.x through 3.7.4. The email module wrongly parses email addresses that contain multiple @ characters. An application that uses the email module and implements some kind of checks on the From/To headers of a message could be tricked into accepting an email address that should be denied. An attack may be the same as in CVE-2019-11340; however, this CVE applies to Python more generally.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "LOW",
            "attackVector": "NETWORK",
            "availabilityImpact": "LOW",
            "baseScore": 7.3,
            "baseSeverity": "HIGH",
            "confidentialityImpact": "LOW",
            "integrityImpact": "LOW",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
            "version": "3.0",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Important"
        }
      ],
      "title": "CVE-2019-16056"
    },
    {
      "cve": "CVE-2019-16935",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2019-16935"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "The documentation XML-RPC server in Python through 2.7.16, 3.x through 3.6.9, and 3.7.x through 3.7.4 has XSS via the server_title field. This occurs in Lib/DocXMLRPCServer.py in Python 2.x, and in Lib/xmlrpc/server.py in Python 3.x. If set_server_title is called with untrusted input, arbitrary JavaScript can be delivered to clients that visit the http URL for this server.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "LOW",
            "attackVector": "NETWORK",
            "availabilityImpact": "NONE",
            "baseScore": 6.1,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "LOW",
            "integrityImpact": "LOW",
            "privilegesRequired": "NONE",
            "scope": "CHANGED",
            "userInteraction": "REQUIRED",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
            "version": "3.1",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Moderate"
        }
      ],
      "title": "CVE-2019-16935"
    },
    {
      "cve": "CVE-2019-9636",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2019-9636"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "Python 2.7.x through 2.7.16 and 3.x through 3.7.2 is affected by: Improper Handling of Unicode Encoding (with an incorrect netloc) during NFKC normalization. The impact is: Information disclosure (credentials, cookies, etc. that are cached against a given hostname). The components are: urllib.parse.urlsplit, urllib.parse.urlparse. The attack vector is: A specially crafted URL could be incorrectly parsed to locate cookies or authentication data and send that information to a different host than when parsed correctly. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.7, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.3, v3.7.3rc1, v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "LOW",
            "attackVector": "NETWORK",
            "availabilityImpact": "HIGH",
            "baseScore": 9.8,
            "baseSeverity": "CRITICAL",
            "confidentialityImpact": "HIGH",
            "integrityImpact": "HIGH",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "version": "3.0",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Critical"
        }
      ],
      "title": "CVE-2019-9636"
    },
    {
      "cve": "CVE-2019-9740",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2019-9740"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "LOW",
            "attackVector": "NETWORK",
            "availabilityImpact": "NONE",
            "baseScore": 6.5,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "LOW",
            "integrityImpact": "LOW",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
            "version": "3.0",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Moderate"
        }
      ],
      "title": "CVE-2019-9740"
    },
    {
      "cve": "CVE-2019-9947",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2019-9947"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the path component of a URL that lacks a ? character) followed by an HTTP header or a Redis command. This is similar to the CVE-2019-9740 query string issue. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "LOW",
            "attackVector": "NETWORK",
            "availabilityImpact": "NONE",
            "baseScore": 6.5,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "LOW",
            "integrityImpact": "LOW",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
            "version": "3.0",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Moderate"
        }
      ],
      "title": "CVE-2019-9947"
    },
    {
      "cve": "CVE-2019-9948",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2019-9948"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "HIGH",
            "attackVector": "NETWORK",
            "availabilityImpact": "NONE",
            "baseScore": 7.4,
            "baseSeverity": "HIGH",
            "confidentialityImpact": "HIGH",
            "integrityImpact": "HIGH",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
            "version": "3.0",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Important"
        }
      ],
      "title": "CVE-2019-9948"
    },
    {
      "cve": "CVE-2020-27619",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2020-27619"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "In Python 3 through 3.9.0, the Lib/test/multibytecodec_support.py CJK codec tests call eval() on content retrieved via HTTP.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "HIGH",
            "attackVector": "NETWORK",
            "availabilityImpact": "HIGH",
            "baseScore": 7.5,
            "baseSeverity": "HIGH",
            "confidentialityImpact": "HIGH",
            "integrityImpact": "HIGH",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "REQUIRED",
            "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
            "version": "3.1",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2020-10-22 03:16:00",
          "details": "Important"
        }
      ],
      "title": "CVE-2020-27619"
    },
    {
      "cve": "CVE-2020-8492",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2020-8492"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "LOW",
            "attackVector": "NETWORK",
            "availabilityImpact": "HIGH",
            "baseScore": 6.5,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "NONE",
            "integrityImpact": "NONE",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "REQUIRED",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
            "version": "3.1",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Moderate"
        }
      ],
      "title": "CVE-2020-8492"
    },
    {
      "cve": "CVE-2021-23336",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2021-23336"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "The package python/cpython from 0 and before 3.6.13, from 3.7.0 and before 3.7.10, from 3.8.0 and before 3.8.8, from 3.9.0 and before 3.9.2 are vulnerable to Web Cache Poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a vector called parameter cloaking. When the attacker can separate query parameters using a semicolon (;), they can cause a difference in the interpretation of the request between the proxy (running with default configuration) and the server. This can result in malicious requests being cached as completely safe ones, as the proxy would usually not see the semicolon as a separator, and therefore would not include it in a cache key of an unkeyed parameter.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "HIGH",
            "attackVector": "NETWORK",
            "availabilityImpact": "HIGH",
            "baseScore": 5.9,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "NONE",
            "integrityImpact": "LOW",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "REQUIRED",
            "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:H",
            "version": "3.1",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Moderate"
        }
      ],
      "title": "CVE-2021-23336"
    },
    {
      "cve": "CVE-2021-3177",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2021-3177"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "Python 3.x through 3.9.1 has a buffer overflow in PyCArg_repr in _ctypes/callproc.c, which may lead to remote code execution in certain Python applications that accept floating-point numbers as untrusted input, as demonstrated by a 1e300 argument to c_double.from_param. This occurs because sprintf is used unsafely.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "HIGH",
            "attackVector": "NETWORK",
            "availabilityImpact": "HIGH",
            "baseScore": 5.9,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "NONE",
            "integrityImpact": "NONE",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "version": "3.1",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Moderate"
        }
      ],
      "title": "CVE-2021-3177"
    },
    {
      "cve": "CVE-2021-3426",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2021-3426"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "LOW",
            "attackVector": "ADJACENT_NETWORK",
            "availabilityImpact": "NONE",
            "baseScore": 5.7,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "HIGH",
            "integrityImpact": "NONE",
            "privilegesRequired": "LOW",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "version": "3.1",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Moderate"
        }
      ],
      "title": "CVE-2021-3426"
    },
    {
      "cve": "CVE-2022-0391",
      "ids": [
        {
          "system_name": "OpenAnolis CVE Page",
          "text": "https://anas.openanolis.cn/cves/detail/CVE-2022-0391"
        }
      ],
      "notes": [
        {
          "category": "description",
          "text": "A flaw was found in Python, specifically within the urllib.parse module. This module helps break Uniform Resource Locator (URL) strings into components. The issue involves how the urlparse method does not sanitize input and allows characters like '\\r' and '\\n' in the URL path. This flaw allows an attacker to input a crafted URL, leading to injection attacks. This flaw affects Python versions prior to 3.10.0b1, 3.9.5, 3.8.11, 3.7.11 and 3.6.14.",
          "title": "Vulnerability description"
        },
        {
          "category": "general",
          "text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
          "title": "CVSS score applicability"
        }
      ],
      "product_status": {
        "fixed": [
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
          "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
        ]
      },
      "references": [
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        },
        {
          "RefID": "",
          "RefURL": "",
          "Source": ""
        }
      ],
      "remediations": [
        {
          "category": "vendor_fix",
          "details": "To fix this cve, please use the installation method recommended by Anolis: find the corresponding system's errata on the cve page, and then use errata to fix it. For details, please refer to references. For example, to fix a cve on Anolis OS 23: yum update --advisory ANSA-2024: xxxx",
          "product_ids": [
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-debug-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:platform-python-devel-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-3.6.8-47.0.1.an8_6.src",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-idle-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-libs-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-test-3.6.8-47.0.1.an8_6.x86_64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.aarch64",
            "Anolis OS 8:python3-tkinter-3.6.8-47.0.1.an8_6.x86_64"
          ]
        }
      ],
      "scores": [
        {
          "cvss_v3": {
            "attackComplexity": "LOW",
            "attackVector": "NETWORK",
            "availabilityImpact": "NONE",
            "baseScore": 5.3,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "NONE",
            "integrityImpact": "LOW",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            "version": "3.1",
            "products": null
          }
        }
      ],
      "threats": [
        {
          "category": "impact",
          "date": "2022-09-21 10:44:40",
          "details": "Moderate"
        }
      ],
      "title": "CVE-2022-0391"
    }
  ]
}